name: Run Private Workflow

on:
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 370
    permissions:
      contents: read

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: your-username/your-private-repo
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: .priv
          persist-credentials: false

      - name: Run private script
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
          COUNTRIES: ${{ secrets.COUNTRIES }}
        run: |
          chmod +x .priv/park.sh
          .priv/park.sh
